### ISSUE TITLE
Cannot find module AreasDB

### ISSUE THREAD

**Issue by Shinnonda** [runi95/turtle-control-panel#2]
I saw the closed issue and tried to follow it, but i got the following error when running `node src` :

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module './db/AreasDB'
Require stack:
- /home/aira/Downloads/TurtleOS/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/aira/Downloads/TurtleOS/src/index.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/aira/Downloads/TurtleOS/src/index.js' ]
}

```

**Comment by runi95** [comment]
This issue stemmed from a typo in index.js and me running the server on Windows which is not case-sensitive and thus I never encountered the problem myself.

Should be fixed now with god-ferny's PR merged.
